version: '3.8'
services:
  weather-project:
    container_name: weather-project
    build: .
    command: bash -c "python weatherproject/manage.py runscript load_historical_records && python weatherproject/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DATA_DIR=wx_data