# Generated by Django 4.2 on 2023-05-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(max_length=11)),
                ('year', models.PositiveSmallIntegerField()),
                ('avg_max_temperature', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('avg_min_temperature', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('total_precipitation', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'unique_together': {('station_code', 'year')},
            },
        ),
    ]
